Feature/url search
kebblar/petstore-back pull request #290
Opened 2021-06-26 20:13 UTC by arellano-gustavo

Se incorpora un endpoint que puede mostrar un anuncio basado en su titulo "normalizado".

2021-06-26 20:16 UTC, arellano-gustavo commented
OJO !!!!! La base de datos cambió y ahora la tabla "Anuncio" tiene un nuevo campo llamado: "search_url":
<img width="603" alt="imagen" src="https://user-images.githubusercontent.com/17259655/123524666-7e26b500-d691-11eb-8bfb-ca3ae0a9efc9.png">

2021-06-26 20:19 UTC, arellano-gustavo commented
Esta rama contiene una copia del script de creación y llenado de la base en el archivo db.sql en:

<img width="304" alt="imagen" src="https://user-images.githubusercontent.com/17259655/123524733-e4133c80-d691-11eb-88d0-10af4d9710db.png">

2021-06-26 20:26 UTC, arellano-gustavo commented
Les ruego que se BAJEN esta rama a su local y RESTAUREN la base de datos con la que tiene esta rama en db.sql
Luego, pueden probar con: 

`curl http://localhost:9999/api/content/post/18-lindo-pez-dorado
`

O con cualquier otro valor que se encuentre en la columna de search_url:

<img width="598" alt="imagen" src="https://user-images.githubusercontent.com/17259655/123524882-bc70a400-d692-11eb-9065-4be817e47b60.png">

2021-06-26 22:45 UTC, mentesniker commented
Pues... parece que el script que esta en la rama feature/url-search no tiene la tabla de anuncio actualizada....
![Screenshot from 2021-06-26 17-44-15](https://user-images.githubusercontent.com/35209340/123527533-33636800-d6a6-11eb-9874-288169e6c743.png)

2021-06-27 06:49 UTC, arellano-gustavo commented
Desde mi perspectiva, este PR sólo contiene dos archivs que se deben revisar con cuidado:
- AnuncioMappper
- AnuncioServiceImpl
Es evidente que el resto de archivos son muy simples y sus cambios extremadamente sencillos

2021-06-27 07:01 UTC, arellano-gustavo commented
@mentesniker : Ya quedó actualizada la base de datos en esa rama.
Una disculpa por el olvido. Excelente anotación. Muchas Gracias !!!!!

2021-06-27 21:46 UTC, fherevans requested changes
Revisado!!

2021-06-27 21:46 UTC, fherevans commented on src/main/java/io/kebblar/petstore/api/service/AnuncioService.java
> +     * Busca los anuncios que pseen el url dado
Javadoc debería ser más específico, falta @Param, @Throws y @Return

2021-06-27 21:46 UTC, fherevans commented on src/main/java/io/kebblar/petstore/api/rest/AnuncioController.java
> +        //anuncioService.updateSearchUrl();
Esta línea comentada puede borrarse

2021-06-27 22:48 UTC, mentesniker commented
It works!!! 
![Screenshot from 2021-06-27 17-47-43](https://user-images.githubusercontent.com/35209340/123561742-daf89d00-d76f-11eb-9f30-3407855298ae.png)

2021-06-27 22:53 UTC, mentesniker commented on src/main/java/io/kebblar/petstore/api/mapper/AnuncioMapper.java
> +    @ResultMap("AnuncioMap")
concuerdo con @fherevans

2021-06-28 00:05 UTC, fherevans commented on src/main/java/io/kebblar/petstore/api/mapper/AnuncioMapper.java
> +    @ResultMap("AnuncioMap")
done

2021-06-28 00:08 UTC, fherevans commented on src/main/java/io/kebblar/petstore/api/service/AnuncioService.java
> +     * Busca los anuncios que pseen el url dado
done

2021-06-28 02:28 UTC, merged